get:
  deprecated: false
  description: Gets the information about an specific training and its performance metrics.
  operationId: getTraining
  responses:
    '200':
      description: >-
        Retreives the created, updated or requested record query for `Training`
        into a `APIResponse` schema.
      content:
        application/json:
          schema:
            type: object
            description: >-
              Returns an APIResponse with Response schema as `data` on
              successful operation.
            properties:
              code:
                description: HTTP code
                type: integer
                format: int32
                example: 200
              message:
                description: '''OK'' or additional information'
                type: string
                example: OK
              data:
                $ref: ../components/schemas/Training.yaml
    '403':
      description: '**Forbidden**: this operation requeris authentication'
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorResponse.yaml
          example:
            code: 403
            message: Error - Forbidden
    '404':
      description: '**Not found**: the resource was not found'
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorResponse.yaml
          example:
            code: 404
            message: Error - Not found
    default:
      description: '**Unexpected error**'
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorResponse.yaml
  summary: Find one training
  tags:
    - Training
  parameters:
    - name: id
      in: path
      description: Training Id
      deprecated: false
      required: true
      schema:
        type: string
