language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && yarn add speccy
  - npx @redocly/openapi-cli bundle openapi/openapi.yaml -o spec/openapi.json
  - yarn prettier --write spec/openapi.json
  - yarn speccy lint spec/openapi.json
  - yarn oas3-mdx --spec spec/openapi.json --target docs/paths --templates md-templates --snippets "shell,node,python,php"
  - yarn GIT_USER="${GH_NAME}" deploy
